import type { CopyKey } from "./Copy";

export const ChineseCopy: Partial<Record<CopyKey, string>> = {
    UserInstructions1: "你可以创建 AI 将遵循的自定义",
    UserInstructions2: "指令",
    UserInstructions3: "。",
    NoUserInstruction: "无自定义指令",

    SettingLanguage: "语言",
    SettingLanguageDesc: "选择插件界面使用的语言。",
    LanguageEnglish: "English",
    LanguageChinese: "简体中文",
    SettingModelProviders: "模型供应商",
    SettingModelProvidersDesc: "添加 Responses API 供应商。每个供应商可使用不同的地址、令牌、模型列表和流式模式。",
    SettingAddProvider: "添加供应商",
    SettingAddProviderDesc: "添加另一个模型供应商或中转服务。",
    SettingModelAssignments: "模型分配",
    SettingModelAssignmentsDesc: "为每种任务选择任意供应商下的模型。",
    SettingMainModel: "主模型",
    SettingMainModelDesc: "用于普通对话和笔记库操作。",
    SettingPlanningRoleModel: "规划模型",
    SettingPlanningRoleModelDesc: "用于复杂任务的规划与编排。",
    SettingQuickRoleModel: "快速工具模型",
    SettingQuickRoleModelDesc: "用于快速操作和生成对话标题。",
    SettingProviderName: "供应商名称",
    SettingProviderNameDesc: "用于在模型选择框中分组显示的名称。",
    SettingBaseUrl: "基础地址（Base URL）",
    SettingBaseUrlDesc: "可填写以 /v1 结尾的基础地址，或完整的 /v1/responses 地址。",
    SettingProviderToken: "API 密钥 / 令牌",
    SettingProviderTokenDesc: "仅用于此供应商的 Bearer 令牌。",
    SettingModelIds: "模型 ID",
    SettingModelIdsDesc: "每行填写一个模型 ID；插件会按原样发送给此供应商。",
    SettingStreamingResponses: "流式响应",
    SettingStreamingResponsesDesc: "仅在供应商支持 Responses API SSE 流式传输和浏览器 CORS 时开启。关闭后将使用 requestUrl() 兼容模式并整段返回。",
    TooltipDeleteProvider: "删除供应商",
    TooltipShowToken: "显示令牌",
    PlaceholderProviderName: "我的供应商",
    PlaceholderProviderToken: "输入令牌",
    NoModelsConfigured: "尚未配置模型",
    UnnamedProvider: "未命名供应商",
    GreetingMorning: "早上好！我们开始吧？",
    GreetingMidday: "你好！今天需要我帮你做什么？",
    GreetingEvening: "晚上好！有什么可以帮你？",
    GreetingNight: "还在挑灯夜战吗？我来帮你。",
    ButtonCollapsePlan: "收起计划步骤",
    ButtonExpandPlan: "展开计划步骤",
    PluginBannerAlt: "插件横幅",

    SettingModel: "模型",
    SettingPlanningModel: "规划模型",
    SettingApiKey: "网关令牌",
    SettingOpenClawUrl: "OpenClaw Responses 地址",
    SettingOpenClawUrlDesc: "完整的 /v1/responses 地址。安卓端应使用手机可以访问的 HTTPS 或 Tailscale 地址；127.0.0.1 仅适用于 OpenClaw 与客户端在同一设备上运行。",
    SettingOpenClawModel: "OpenClaw 模型",
    SettingOpenClawModelDesc: "主模型 ID，例如 openclaw/default 或 openclaw/<agentId>。",
    SettingOpenClawPlanningModel: "规划模型 ID",
    SettingOpenClawPlanningModelDesc: "规划和编排使用的可选模型 ID；留空则使用主模型。",
    SettingOpenClawQuickActionModel: "快速工具模型 ID",
    SettingOpenClawQuickActionModelDesc: "快速操作与对话标题使用的可选模型 ID；留空则使用主模型。",
    SettingOpenClawCompatibilityMode: "非流式兼容模式",
    SettingOpenClawCompatibilityModeDesc: "使用 Obsidian requestUrl() 绕过浏览器 CORS 限制。响应完成后一次性显示。",
    SettingFileExclusions: "文件排除规则",
    SettingFileExclusionsDesc: "设置 AI 应忽略的目录和文件，每行一个路径；支持 folder/**、*.md 等 glob 规则。",
    SettingContext: "上下文",
    SettingSearchResultsLimit: "搜索结果上限",
    SettingSearchResultsLimitDesc: "设置搜索笔记库时提供给 AI 的最大结果数。数值越高，上下文越丰富，但搜索耗时也可能增加。",
    SettingSnippetSizeLimit: "摘要长度上限",
    SettingSnippetSizeLimitDesc: "设置每条搜索预览提供给 AI 的字符数。",
    SettingFileMonitoringHeading: "文件监控说明",
    SettingMemories: "记忆",
    SettingEnableMemories: "启用记忆",
    SettingEnableMemoriesDesc: "允许 AI 调用以前对话中保存的记忆。",
    SettingAllowUpdatingMemories: "允许更新记忆",
    SettingAllowUpdatingMemoriesDesc: "允许 AI 保存和更新对话记忆。",
    SettingWebViewerAccess: "网页查看器访问",
    SettingEnableWebViewer: "启用网页查看器访问",
    SettingEnableWebViewerDesc: "允许 AI 读取 Obsidian 网页查看器中打开的页面；这与输入栏中的联网搜索开关不同。",
    SettingModelDesc: "选择要使用的 AI 模型。",
    SettingPlanningModelDesc: "选择规划复杂任务时使用的 AI 模型。",
    SettingPlanningModelTip: "提示：可使用更强的模型负责规划、较便宜的模型负责日常执行。",
    SettingQuickActionModel: "快速工具模型",
    SettingQuickActionModelDesc: "选择快速操作使用的模型，建议使用速度快、成本低的模型。",
    SettingApiKeyDesc: "输入用于 Bearer 身份验证的 OpenClaw 网关令牌或密码。",
    SettingAccessMemories: "记忆可让 AI 跨对话保留偏好和背景信息，你可以随时查看和编辑。",
    CommandQuickActionPrefix: "Vaultkeeper：",

    SettingAdvancedSettings: "高级设置",
    SettingHideDrawerElements: "输入时隐藏侧栏元素",
    SettingHideDrawerElementsDesc: "在移动设备弹出键盘时隐藏侧栏元素，以提供更多输入空间；输入框失去焦点后会重新显示。",
    SettingQuickActions: "快速操作",
    SettingEnableContextMenuActions: "启用右键菜单操作",
    SettingEnableContextMenuActionsDesc: "在编辑器右键菜单中显示 AI 快速操作。",
    SettingEnableToolbarActions: "启用工具栏操作",
    SettingEnableToolbarActionsDesc: "在编辑器工具栏中显示适合移动端使用的 AI 快速操作按钮。",
    PlaceholderEnterApiKey: "输入网关令牌",
    PlaceholderFileExclusions: "示例：\n\nprivate/**\n*.secret.md\njournal/personal/**",
    TooltipShowApiKey: "显示 API 密钥",
    TooltipHideApiKey: "隐藏 API 密钥",
    TooltipLearnMoreFileMonitoring: "在插件指南中了解更多",
    TooltipAccessMemories: "查看记忆",

    AIThoughtMessage: "思考中……",
    AIThoughtGeneratingNote: "正在生成笔记内容……",
    AIThoughtPreparingQuery: "正在准备问题……",
    PlanningInProgress: "正在规划……",
    RateLimitCountdown: "请求频率受限，{0} 秒后重试……",
    RateLimitInfo1: "如果经常遇到频率限制，请查看 ",
    RateLimitInfoLink: "API 等级",
    RateLimitInfo2: "。",
    SafeContinue: "继续",
    ChatModeReadOnlyTitle: "只读",
    ChatModeReadOnlyDesc: "AI 可以搜索和读取笔记库，但不能修改内容。",
    ChatModeEditTitle: "允许编辑",
    ChatModeEditDesc: "AI 可以创建、编辑、移动和删除笔记库文件。",
    ChatModePlanningTitle: "规划",
    ChatModePlanningDesc: "AI 会先制定计划，再执行复杂的笔记库任务。",
    InputPlaceholderQuestion: "请输入回答……",
    InputPlaceholderDiff: "请输入修改建议……",
    InputPlaceholderNormal: "输入消息……",
    InputPlaceholderCompact: "消息……",
    InputPlaceholderQuestionCompact: "回答……",
    InputPlaceholderDiffCompact: "建议……",
    ButtonCancel: "取消",
    ButtonSubmitAnswer: "提交回答",
    ButtonMakeSuggestion: "提交建议",
    ButtonSendMessage: "发送消息",
    ButtonChangeChatMode: "切换对话模式",
    ButtonTurnOffPlanningMode: "关闭规划模式",
    ButtonTurnOnPlanningMode: "开启规划模式",
    ButtonTurnOffWebSearch: "关闭联网搜索",
    ButtonTurnOnWebSearch: "开启联网搜索",
    ButtonUserInstruction: "用户指令",
    ButtonAttachFiles: "添加附件",
    ButtonNewConversation: "新建对话",
    ButtonDeleteConversation: "删除对话",
    ButtonConversationHistory: "对话历史",
    ButtonSettings: "Vaultkeeper OpenClaw 设置",
    ButtonHelp: "帮助",
    ButtonClosePlugin: "关闭 Vaultkeeper OpenClaw",
    ButtonRemoveAttachment: "移除附件",
    ButtonScrollToBottom: "滚动到底部",
    ButtonAccept: "接受",
    ButtonReject: "拒绝",
    ButtonDeleteSelectedConversations: "删除选中的对话",
    ButtonSearchConversations: "搜索对话",
    ButtonCloseConversationHistory: "关闭对话历史",
    QuickActionProofread: "校对",
    QuickActionBeautify: "润色",
    QuickActionApplyTemplate: "应用模板",
    QuickActionApplyLinks: "添加链接",
    QuickActionApplyTags: "添加标签",
    QuickActionSuggestTags: "推荐标签",
    QuickActionGenerateFrontmatter: "生成 Frontmatter",
    QuickActionMenu: "快速操作",
    QuickActionAriaLabel: "AI 快速操作",
    QuickActionProofreading: "正在校对……",
    QuickActionBeautifying: "正在润色内容……",
    QuickActionApplyingTemplate: "正在应用模板……",
    QuickActionApplyingLinks: "正在添加链接……",
    QuickActionApplyingTags: "正在添加标签……",
    QuickActionSuggestingTags: "正在推荐标签……",
    QuickActionGeneratingFrontmatter: "正在生成 Frontmatter……",
    QuickActionTimedOut: "快速操作“{0}”超时",
    ErrorUnsupportedFile: "不支持的文件“{0}”",
    ErrorOpenNote: "无法打开笔记：“{0}”",
    ErrorDeleteConversation: "无法删除对话“{0}”",
    ErrorDeleteConversationData: "无法删除对话数据：“{0}”",
    ErrorPlugin: "Vaultkeeper OpenClaw 错误：{0}",
    ErrorSaveConversation: "无法保存对话数据：“{0}”",
    ErrorLoadConversation: "无法加载对话“{0}”",
    ErrorNameConversation: "无法为对话“{0}”生成标题",
    MediaOpen: "打开文件",
    MediaFailed: "媒体不可用",
    MediaDownloadFailed: "媒体下载失败",
    MediaTooLarge: "媒体文件过大",
    MediaFormatUnsupported: "该格式不支持预览",
    AttachedFile: "附件：{0}",

    PlanningFailedError: "规划失败，请重试。",
    ContinuePlanExecution: "继续执行计划",
    PlanExecutionCancelled: "计划执行已取消。",
    PlanningFailedNoSteps: "规划失败：没有生成可执行步骤。",
    PlanningModeError: "规划模式发生错误。",
    WorkflowFailedAtStep: "工作流在步骤“{0}”处失败。",
    WorkflowAborted: "工作流已中止：{0}",
    PlanReceived: "已收到计划。",
    MaxExecutionDepthReached: "已达到最大执行深度。",
    MemoriesEmpty: "目前没有保存的记忆。",
    MemoriesMaxLengthError: "记忆内容超过最大长度（{0}）。",
    MemoriesUpdatedSuccess: "记忆已更新。",
    MemoriesDisabledError: "记忆功能当前未启用。",
    MemoriesUpdatingDisabledError: "当前不允许更新记忆。",
    UpdateMemoriesWithoutReadError: "更新记忆前必须先读取现有记忆。",
    WebViewerNoMatchingUrl: "未找到与“{0}”匹配的网页查看器页面。",
    WebViewerNoOpenView: "当前没有打开的网页查看器页面。",
    ApplyTemplateCancelled: "模板应用已取消。",

    HelpModalAboutTitle: "关于",
    HelpModalAboutContent: `## Vaultkeeper OpenClaw\n\n这是一个连接 OpenClaw Responses API 与 Obsidian 笔记库的 AI 助手。它可以在你授权的模式下搜索、读取、创建、编辑、移动和删除笔记。`,
    HelpModalGettingStartedTitle: "快速开始",
    HelpModalGettingStartedContent: `## 快速开始\n\n1. 在设置中添加模型供应商，填写 Base URL、令牌和模型 ID。\n2. 为主模型、规划模型和快速工具模型进行分配。\n3. 打开侧栏，选择只读、编辑或规划模式。\n4. 输入消息开始使用。`,
    HelpModalChatModesTitle: "对话模式",
    HelpModalChatModesContent: `## 对话模式\n\n- **只读**：只能搜索和读取笔记。\n- **允许编辑**：可以创建、修改、移动和删除文件。\n- **规划**：先生成多步骤计划，再逐步执行。`,
    HelpModalReferenceTitle: "引用笔记库内容",
    HelpModalReferenceContent: `## 引用\n\n在输入框中使用 **@** 引用文件、使用 **#** 引用标签、使用 **/** 引用文件夹。引用内容会作为本次请求的上下文。`,
    HelpModalCustomInstructionsTitle: "自定义指令",
    HelpModalCustomInstructionsContent: `## 自定义指令\n\n你可以创建可重复使用的用户指令，用于约定语言、写作风格、格式和工作方式。`,
    HelpModalQuickActionsTitle: "快速操作",
    HelpModalQuickActionsContent: `## 快速操作\n\n可从编辑器右键菜单或工具栏对选中文本执行润色、校对、添加链接、标签和 frontmatter 等操作。`,
    HelpModalUploadedFilesTitle: "附件",
    HelpModalUploadedFilesContent: `## 附件\n\n可以通过附件按钮、拖放或粘贴添加图片和文件。附件会随对话保存，并根据供应商能力发送给模型。请勿上传不希望交给模型供应商处理的敏感内容。`,
    HelpModalTroubleshootTitle: "故障排查",
    HelpModalTroubleshootContent: `## 故障排查\n\n遇到网络错误时，请检查供应商 Base URL、令牌、模型 ID、流式与 CORS 设置。Tailscale Serve 通常应关闭流式响应以使用 requestUrl() 兼容模式。`,
    HelpModalPrivacyTitle: "隐私",
    HelpModalPrivacyContent: `## 隐私\n\n对话、引用和附件可能会发送给你配置的模型供应商。笔记库修改由本地 Obsidian 客户端工具执行。请阅读并确认所用供应商的数据保留政策。`,
    NoConversationsFound: "未找到对话",
    ConversationDate: "日期",
    ConversationTitle: "标题",
    HelpModalCloseAriaLabel: "关闭帮助",
    PluginVersionPrefix: "插件版本：",
    GitHubLinkText: "在 GitHub 上查看项目",
    GitHubIconAriaLabel: "GitHub",
    CoffeeLinkIntroText: "如果这个插件对你有帮助：",
    CoffeeLinkText: "请作者喝杯咖啡",
    ThankYouMessage: "感谢你的支持！",

    // S3 存储
    SettingS3Storage: "S3 存储",
    SettingS3StorageDesc: "配置文件附件的 S3 兼容存储。",
    SettingS3Enabled: "启用 S3 存储",
    SettingS3Endpoint: "终端节点",
    SettingS3EndpointDesc: "S3 终端节点 URL，例如 https://s3.amazonaws.com",
    SettingS3Bucket: "存储桶",
    SettingS3BucketDesc: "S3 存储桶名称",
    SettingS3Region: "区域",
    SettingS3RegionDesc: "S3 区域，例如 us-east-1",
    SettingS3AccessKey: "访问密钥",
    SettingS3AccessKeyDesc: "AWS 访问密钥 ID",
    SettingS3SecretKey: "秘密密钥",
    SettingS3SecretKeyDesc: "AWS 秘密访问密钥",
    SettingS3PathPrefix: "路径前缀",
    SettingS3PathPrefixDesc: "上传文件的可选路径前缀",
    SettingS3PublicUrlBase: "公开 URL 基础",
    SettingS3PublicUrlBaseDesc: "可选的自定义公开 URL 基础（用于 CDN）",
    SettingS3TestConnection: "测试连接",
    SettingS3ConnectionSuccess: "连接成功",
    SettingS3ConnectionFailed: "连接失败",

    // 自定义技能
    SettingCustomSkills: "自定义技能",
    SettingCustomSkillsDesc: "管理内置快速操作，并使用自定义提示词定义你自己的技能。",
    SettingBuiltInSkill: "内置",
    SettingBuiltInSkillPromptManaged: "这个内置技能使用 Vaultkeeper 管理的专用动作逻辑。",
    SettingBuiltInSkillNotEditable: "内置技能可以启用/禁用和指定模型，但提示词与行为由插件管理。",
    SettingUseDefaultQuickActionModel: "使用默认快速工具模型",
    SettingAddSkill: "添加技能",
    SettingSkillName: "技能名称",
    SettingSkillIcon: "图标",
    SettingSkillPrompt: "提示词",
    SettingSkillPromptDesc: "使用 {{selection}}、{{file_content}}、{{file_name}}、{{tags}}、{{title}} 作为占位符。",
    SettingSkillModel: "模型",
    SettingSkillModelDesc: "可选：留空以使用默认快速操作模型。",
    SettingSkillOutputMode: "输出模式",
    SettingSkillOutputModeReplaceSelection: "替换选中文本",
    SettingSkillOutputModeReplaceBody: "替换正文",
    SettingSkillOutputModeInsertAtCursor: "在光标处插入",
    SettingSkillOutputModeCopyToClipboard: "复制到剪贴板",
    SettingSkillEnabled: "已启用",
    SettingSkillChatEnabled: "用于主对话",
    SettingSkillPinned: "置顶",
    SettingChatSkill: "对话技能",
    SettingChatSkillNone: "无技能",
    SettingChatSkillDesc: "仅对下一条消息应用技能指令。",
    SettingSkillEdit: "编辑",
    SettingSkillDelete: "删除",
    SettingSkillDeleteConfirm: "确定要删除此技能吗？",
    SkillResultCopiedToClipboard: "结果已复制到剪贴板",
    SkillExecuting: "执行中...",
    ConversationHistoryLoading: "正在加载对话历史……",
    ConversationHistoryLoadFailed: "无法加载对话历史",

};
